# Generated by Django 5.0.7 on 2024-07-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="banner",
            field=models.ImageField(blank=True, default="legend.jpg", upload_to=""),
        ),
    ]
